on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Create uv environment
        run: uv venv .venv

      - name: Install pyaudio pre-requisite
        run: sudo apt-get install -y portaudio19-dev

      - name: Install dependencies
        run: . .venv/bin/activate && uv pip install -r Agent/req.txt

      - name: Install PyTorch with CUDA 12.6
        run: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126

      - name: Install huggingface_hub
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: . .venv/bin/activate && uv pip install huggingface_hub

      - name: Install bge-large-en-v1.5
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: . .venv/bin/activate && .venv/bin/huggingface-cli download BAAI/bge-large-en-v1.5 --local-dir Agent/cached_embedding_model --token $HUGGINGFACE_TOKEN

      - name : remove cach and un used docker images - containers 
        run : docker system prune -a -f && docker container prune -f && docker image prune -f && docker builder prune --all -f

      - name : login to docker hub
        run : echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build --build-arg HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }} -t abdelrahmanmostafamohamed/dataverse_agents:latest .

      - name: Run Docker container
        run: docker run -d -p 9000:9000 yabdelrahmanmostafamohamed/dataverse_agents:latest

      - name: Wait for API to start
        run: sleep 10 # Adjust as needed

      - name: Test API
        run: curl http://localhost:9000/ 